general.import = [ "~/.config/alacritty/themes/themes/catppuccin_mocha.toml" ]

[window]
opacity = 0.80

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

