import = [ "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml" ]

[window]
opacity = 0.80

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

